# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DwpV-T2tzrMgyq2JKROdCk5Ux3wwe4em
"""

pip install gradio

"""##CNN APP"""

import gradio as gr
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import numpy as np

# Load the saved CNN model
model = load_model('/content/drive/MyDrive/Model weights/currency_cnn_model.h5')  # Path to your saved model
print("CNN model loaded successfully!")

# Function to preprocess and predict
def predict_currency(image):
    # Resize image to 224x224 (same as training)
    img = image.resize((224, 224))
    # Convert to array and normalize
    img_array = img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)  # Add batch dimension

    # Make prediction
    prediction = model.predict(img_array)[0][0]
    # Convert to label and confidence
    label = 'Genuine' if prediction > 0.5 else 'Fake'
    confidence = prediction * 100 if label == 'Genuine' else (1 - prediction) * 100

    # Return result as a string
    return f"Prediction: {label}\nConfidence: {confidence:.2f}%"

# Create Gradio interface
interface = gr.Interface(
    fn=predict_currency,  # Prediction function
    inputs=gr.Image(type="pil", label="Upload a Currency Image"),  # Input: Image upload
    outputs=gr.Textbox(label="Result"),  # Output: Text with prediction
    title="Currency Authenticity Detector",
    description="Upload an image of a banknote to check if it's genuine or fake using a CNN model."
)

# Launch the interface
interface.launch()

"""##VGG APP"""

import gradio as gr
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import numpy as np

# Load the saved CNN model
model = load_model('/content/drive/MyDrive/Model weights/VGG16_currency_model.h5')  # Path to your saved model
print("VGG model loaded successfully!")

# Function to preprocess and predict
def predict_currency(image):
    # Resize image to 224x224 (same as training)
    img = image.resize((224, 224))
    # Convert to array and normalize
    img_array = img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)  # Add batch dimension

    # Make prediction
    prediction = model.predict(img_array)[0][0]
    # Convert to label and confidence
    label = 'Genuine' if prediction > 0.5 else 'Fake'
    confidence = prediction * 100 if label == 'Genuine' else (1 - prediction) * 100

    # Return result as a string
    return f"Prediction: {label}\nConfidence: {confidence:.2f}%"

# Create Gradio interface
interface = gr.Interface(
    fn=predict_currency,  # Prediction function
    inputs=gr.Image(type="pil", label="Upload a Currency Image"),  # Input: Image upload
    outputs=gr.Textbox(label="Result"),  # Output: Text with prediction
    title="Currency Authenticity Detector",
    description="Upload an image of a banknote to check if it's genuine or fake using a VGG model."
)

# Launch the interface
interface.launch()

"""##ResNet APP"""

import gradio as gr
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import numpy as np

# Load the saved CNN model
model = load_model('/content/drive/MyDrive/Model weights/ResNet50_currency_model.h5')  # Path to your saved model
print("ResNet model loaded successfully!")

# Function to preprocess and predict
def predict_currency(image):
    # Resize image to 224x224 (same as training)
    img = image.resize((224, 224))
    # Convert to array and normalize
    img_array = img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)  # Add batch dimension

    # Make prediction
    prediction = model.predict(img_array)[0][0]
    # Convert to label and confidence
    label = 'Genuine' if prediction > 0.5 else 'Fake'
    confidence = prediction * 100 if label == 'Genuine' else (1 - prediction) * 100

    # Return result as a string
    return f"Prediction: {label}\nConfidence: {confidence:.2f}%"

# Create Gradio interface
interface = gr.Interface(
    fn=predict_currency,  # Prediction function
    inputs=gr.Image(type="pil", label="Upload a Currency Image"),  # Input: Image upload
    outputs=gr.Textbox(label="Result"),  # Output: Text with prediction
    title="Currency Authenticity Detector",
    description="Upload an image of a banknote to check if it's genuine or fake using a ResNet model."
)

# Launch the interface
interface.launch()

"""##MobileNet APP"""

import gradio as gr
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import numpy as np

# Load the saved CNN model
model = load_model('/content/drive/MyDrive/Model weights/MobileNetV2_currency_model.h5')  # Path to your saved model
print("MobileNet model loaded successfully!")

# Function to preprocess and predict
def predict_currency(image):
    # Resize image to 224x224 (same as training)
    img = image.resize((224, 224))
    # Convert to array and normalize
    img_array = img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)  # Add batch dimension

    # Make prediction
    prediction = model.predict(img_array)[0][0]
    # Convert to label and confidence
    label = 'Genuine' if prediction > 0.5 else 'Fake'
    confidence = prediction * 100 if label == 'Genuine' else (1 - prediction) * 100

    # Return result as a string
    return f"Prediction: {label}\nConfidence: {confidence:.2f}%"

# Create Gradio interface
interface = gr.Interface(
    fn=predict_currency,  # Prediction function
    inputs=gr.Image(type="pil", label="Upload a Currency Image"),  # Input: Image upload
    outputs=gr.Textbox(label="Result"),  # Output: Text with prediction
    title="Currency Authenticity Detector",
    description="Upload an image of a banknote to check if it's genuine or fake using a MobileNet model."
)

# Launch the interface
interface.launch()